import { BlockVariation } from '@wordpress/blocks';
import { __ } from '@wordpress/i18n';

export const variations: BlockVariation[] = [
  {
    name: 'text-field',
    title: __('Text', 'usm'),
    description: __('Display a text field.', 'usm'),
    scope: [],
    isActive: attributes => attributes?.fieldSettings?.type === 'text',
  },
  {
    name: 'textarea-field',
    title: __('Textarea', 'usm'),
    description: __('Display a textarea field.', 'usm'),
    scope: [],
    isActive: attributes => attributes?.fieldSettings?.type === 'textarea',
  },
  {
    name: 'image-field',
    title: __('Image', 'usm'),
    description: __('Display a image field.', 'usm'),
    scope: [],
    isActive: attributes => attributes?.fieldSettings?.type === 'image',
  },
  {
    name: 'link-field',
    title: __('Link', 'usm'),
    description: __('Display a link field.', 'usm'),
    scope: [],
    isActive: attributes => attributes?.fieldSettings?.type === 'link',
  },
  {
    name: 'select-field',
    title: __('Select', 'usm'),
    description: __('Display a select field.', 'usm'),
    scope: [],
    isActive: attributes => attributes?.fieldSettings?.type === 'select',
  },
  {
    name: 'true_false-field',
    title: __('True/false', 'usm'),
    description: __('Display a true/false field.', 'usm'),
    scope: [],
    isActive: attributes => attributes?.fieldSettings?.type === 'true_false',
  },
  {
    name: 'wysiwyg-field',
    title: __('Editor', 'usm'),
    description: __('Display a wysiwyg field.', 'usm'),
    scope: [],
    isActive: attributes => attributes?.fieldSettings?.type === 'wysiwyg',
  },
  {
    name: 'relationship-field',
    title: __('Relationship', 'usm'),
    description: __('Display a relationship field.', 'usm'),
    scope: [],
    isActive: attributes => attributes?.fieldSettings?.type === 'relationship',
  },
  {
    name: 'post_object-field',
    title: __('Post Object', 'usm'),
    description: __('Display a post object field.', 'usm'),
    scope: [],
    isActive: attributes => attributes?.fieldSettings?.type === 'post_object',
  },
  {
    name: 'number-field',
    title: __('Number', 'usm'),
    description: __('Display a number field.', 'usm'),
    scope: [],
    isActive: attributes => attributes?.fieldSettings?.type === 'number',
  },
  {
    name: 'email-field',
    title: __('Email', 'usm'),
    description: __('Display an email field.', 'usm'),
    scope: [],
    isActive: attributes => attributes?.fieldSettings?.type === 'email',
  },
  {
    name: 'url-field',
    title: __('URL', 'usm'),
    description: __('Display a URL field.', 'usm'),
    scope: [],
    isActive: attributes => attributes?.fieldSettings?.type === 'url',
  },
  {
    name: 'oembed-field',
    title: __('Embed', 'usm'),
    description: __('Display an embed field.', 'usm'),
    scope: [],
    isActive: attributes => attributes?.fieldSettings?.type === 'oembed',
  },
  {
    name: 'page_link-field',
    title: __('Page link', 'usm'),
    description: __('Display a page link field.', 'usm'),
    scope: [],
    isActive: attributes => attributes?.fieldSettings?.type === 'page_link',
  },
  {
    name: 'file-field',
    title: __('File', 'usm'),
    description: __('Display a file field.', 'usm'),
    scope: [],
    isActive: attributes => attributes?.fieldSettings?.type === 'file',
  },
];
